### PR TITLE
[WIP] Weights & Biases Logger

### PR DESCRIPTION
**Pull request by digantamisra98**
This PR adds the functionalities of logging experiments on Avalanche using [Weights & Biases](https://wandb.ai/). Current implementation supports logging of all metrics + system metrics + hardware monitoring along with media logging capabilities for confusion matrix. 

This PR is a WIP. The confusion matrix logging is being polished. 

Run demo using the file `wandb_logger.py` in the `examples` folder. The code is essentially ported from `tensorboard_logger.py`, however results in the following error:

```
Starting experiment...
Start of experience:  0
Current Classes:  [4, 5]
-- >> Start of training phase << --
-- Starting training on experience 0 (Task 0) from train stream --
100%|██████████| 113/113 [00:06<00:00, 17.41it/s]
Epoch 0 ended.
	CPUUsage_Epoch/train_phase/train_stream/Task000 = 93.7000
	CPUUsage_MB/train_phase/train_stream/Task000 = 0.0000
	DiskUsage_Epoch/train_phase/train_stream/Task000 = 119708.0713
	DiskUsage_MB/train_phase/train_stream/Task000 = 119708.0029
	Loss_Epoch/train_phase/train_stream/Task000 = 0.7449
	Loss_MB/train_phase/train_stream/Task000 = 0.4048
	MAC_Epoch/train_phase/train_stream/Task000 = 406528
	MAC_MB/train_phase/train_stream/Task000 = 406528
	MaxGPU0Usage_Epoch/train_phase/train_stream/Task000 = 0
	MaxGPU0Usage_MB/train_phase/train_stream/Task000 = 0
	MaxRAMUsage_Epoch/train_phase/train_stream/Task000 = 2407.2656
	MaxRAMUsage_MB/train_phase/train_stream/Task000 = 0
	RunningLoss_Epoch/train_phase/train_stream/Task000 = 0.7449
	Time_Epoch/train_phase/train_stream/Task000 = 6.4883
	Time_MB/train_phase/train_stream/Task000 = 0.0026
	Top1_Acc_Epoch/train_phase/train_stream/Task000 = 0.7140
	Top1_Acc_MB/train_phase/train_stream/Task000 = 0.8413
	Top1_RunningAcc_Epoch/train_phase/train_stream/Task000 = 0.7140
100%|██████████| 113/113 [00:06<00:00, 18.02it/s]
Epoch 1 ended.
	CPUUsage_Epoch/train_phase/train_stream/Task000 = 96.4000
	CPUUsage_MB/train_phase/train_stream/Task000 = 0.0000
	DiskUsage_Epoch/train_phase/train_stream/Task000 = 120215.2148
	DiskUsage_MB/train_phase/train_stream/Task000 = 120215.1465
	Loss_Epoch/train_phase/train_stream/Task000 = 0.3738
	Loss_MB/train_phase/train_stream/Task000 = 0.3676
	MAC_Epoch/train_phase/train_stream/Task000 = 406528
	MAC_MB/train_phase/train_stream/Task000 = 406528
	MaxGPU0Usage_Epoch/train_phase/train_stream/Task000 = 0
	MaxGPU0Usage_MB/train_phase/train_stream/Task000 = 0
	MaxRAMUsage_Epoch/train_phase/train_stream/Task000 = 2407.8516
	MaxRAMUsage_MB/train_phase/train_stream/Task000 = 0
	RunningLoss_Epoch/train_phase/train_stream/Task000 = 0.3738
	Time_Epoch/train_phase/train_stream/Task000 = 6.2751
	Time_MB/train_phase/train_stream/Task000 = 0.0031
	Top1_Acc_Epoch/train_phase/train_stream/Task000 = 0.8540
	Top1_Acc_MB/train_phase/train_stream/Task000 = 0.8889
	Top1_RunningAcc_Epoch/train_phase/train_stream/Task000 = 0.8540
100%|██████████| 113/113 [00:06<00:00, 17.01it/s]
Epoch 2 ended.
	CPUUsage_Epoch/train_phase/train_stream/Task000 = 96.8000
	CPUUsage_MB/train_phase/train_stream/Task000 = 345.1000
	DiskUsage_Epoch/train_phase/train_stream/Task000 = 120725.8975
	DiskUsage_MB/train_phase/train_stream/Task000 = 120725.7451
	Loss_Epoch/train_phase/train_stream/Task000 = 0.2944
	Loss_MB/train_phase/train_stream/Task000 = 0.3209
	MAC_Epoch/train_phase/train_stream/Task000 = 406528
	MAC_MB/train_phase/train_stream/Task000 = 406528
	MaxGPU0Usage_Epoch/train_phase/train_stream/Task000 = 0
	MaxGPU0Usage_MB/train_phase/train_stream/Task000 = 0
	MaxRAMUsage_Epoch/train_phase/train_stream/Task000 = 2407.8516
	MaxRAMUsage_MB/train_phase/train_stream/Task000 = 0
	RunningLoss_Epoch/train_phase/train_stream/Task000 = 0.2944
	Time_Epoch/train_phase/train_stream/Task000 = 6.6413
	Time_MB/train_phase/train_stream/Task000 = 0.0029
	Top1_Acc_Epoch/train_phase/train_stream/Task000 = 0.8926
	Top1_Acc_MB/train_phase/train_stream/Task000 = 0.8571
	Top1_RunningAcc_Epoch/train_phase/train_stream/Task000 = 0.8926
100%|██████████| 113/113 [00:06<00:00, 17.08it/s]
Epoch 3 ended.
	CPUUsage_Epoch/train_phase/train_stream/Task000 = 96.2000
	CPUUsage_MB/train_phase/train_stream/Task000 = 0.0000
	DiskUsage_Epoch/train_phase/train_stream/Task000 = 121236.4980
	DiskUsage_MB/train_phase/train_stream/Task000 = 121236.4297
	Loss_Epoch/train_phase/train_stream/Task000 = 0.2413
	Loss_MB/train_phase/train_stream/Task000 = 0.1922
	MAC_Epoch/train_phase/train_stream/Task000 = 406528
	MAC_MB/train_phase/train_stream/Task000 = 406528
	MaxGPU0Usage_Epoch/train_phase/train_stream/Task000 = 0
	MaxGPU0Usage_MB/train_phase/train_stream/Task000 = 0
	MaxRAMUsage_Epoch/train_phase/train_stream/Task000 = 2408.0859
	MaxRAMUsage_MB/train_phase/train_stream/Task000 = 0
	RunningLoss_Epoch/train_phase/train_stream/Task000 = 0.2413
	Time_Epoch/train_phase/train_stream/Task000 = 6.6128
	Time_MB/train_phase/train_stream/Task000 = 0.0039
	Top1_Acc_Epoch/train_phase/train_stream/Task000 = 0.9167
	Top1_Acc_MB/train_phase/train_stream/Task000 = 0.9524
	Top1_RunningAcc_Epoch/train_phase/train_stream/Task000 = 0.9167
-- >> End of training phase << --
Training completed
Computing accuracy on the whole test set
-- >> Start of eval phase << --
-- Starting eval on experience 0 (Task 0) from test stream --
100%|██████████| 19/19 [00:00<00:00, 26.27it/s]
> Eval on experience 0 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp000 = 99.7000
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp000 = 121252.3506
	Loss_Exp/eval_phase/test_stream/Task000/Exp000 = 0.1345
	MAC_Exp/eval_phase/test_stream/Task000/Exp000 = 406528
	MaxGPU0Usage_Experience/eval_phase/test_stream/Task000/Exp000 = 0
	MaxRAMUsage_Experience/eval_phase/test_stream/Task000/Exp000 = 2408.2383
	Time_Exp/eval_phase/test_stream/Task000/Exp000 = 0.7231
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp000 = 0.9525
-- Starting eval on experience 1 (Task 0) from test stream --
100%|██████████| 21/21 [00:00<00:00, 30.79it/s]
> Eval on experience 1 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp001 = 99.9000
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp001 = 121261.3164
	Loss_Exp/eval_phase/test_stream/Task000/Exp001 = 10.8831
	MAC_Exp/eval_phase/test_stream/Task000/Exp001 = 406528
	MaxGPU0Usage_Experience/eval_phase/test_stream/Task000/Exp001 = 0
	MaxRAMUsage_Experience/eval_phase/test_stream/Task000/Exp001 = 2408.6172
	Time_Exp/eval_phase/test_stream/Task000/Exp001 = 0.6811
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp001 = 0.0000
-- Starting eval on experience 2 (Task 0) from test stream --
100%|██████████| 20/20 [00:00<00:00, 30.68it/s]
> Eval on experience 2 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp002 = 101.4000
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp002 = 121270.2598
	Loss_Exp/eval_phase/test_stream/Task000/Exp002 = 11.2168
	MAC_Exp/eval_phase/test_stream/Task000/Exp002 = 406528
	MaxGPU0Usage_Experience/eval_phase/test_stream/Task000/Exp002 = 0
	MaxRAMUsage_Experience/eval_phase/test_stream/Task000/Exp002 = 2408.6172
	Time_Exp/eval_phase/test_stream/Task000/Exp002 = 0.6511
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp002 = 0.0000
-- Starting eval on experience 3 (Task 0) from test stream --
100%|██████████| 22/22 [00:00<00:00, 30.66it/s]
> Eval on experience 3 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp003 = 99.1000
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp003 = 121279.4014
	Loss_Exp/eval_phase/test_stream/Task000/Exp003 = 8.4918
	MAC_Exp/eval_phase/test_stream/Task000/Exp003 = 406528
	MaxGPU0Usage_Experience/eval_phase/test_stream/Task000/Exp003 = 0
	MaxRAMUsage_Experience/eval_phase/test_stream/Task000/Exp003 = 2408.7227
	Time_Exp/eval_phase/test_stream/Task000/Exp003 = 0.7164
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp003 = 0.0000
-- Starting eval on experience 4 (Task 0) from test stream --
100%|██████████| 20/20 [00:00<00:00, 27.78it/s]
> Eval on experience 4 (Task 0) from test stream ended.
	CPUUsage_Exp/eval_phase/test_stream/Task000/Exp004 = 100.2000
	DiskUsage_Exp/eval_phase/test_stream/Task000/Exp004 = 121288.2930
	Loss_Exp/eval_phase/test_stream/Task000/Exp004 = 10.6322
	MAC_Exp/eval_phase/test_stream/Task000/Exp004 = 406528
	MaxGPU0Usage_Experience/eval_phase/test_stream/Task000/Exp004 = 0
	MaxRAMUsage_Experience/eval_phase/test_stream/Task000/Exp004 = 2408.7227
	Time_Exp/eval_phase/test_stream/Task000/Exp004 = 0.7189
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp004 = 0.0000
Traceback (most recent call last):
  File "wandb_logger.py", line 124, in <module>
    main(args)
  File "wandb_logger.py", line 114, in main
    results.append(cl_strategy.eval(scenario.test_stream))
  File "/content/avalanche/avalanche/training/strategies/base_strategy.py", line 341, in eval
    self.after_eval(**kwargs)
  File "/content/avalanche/avalanche/training/strategies/base_strategy.py", line 529, in after_eval
    p.after_eval(self, **kwargs)
  File "/content/avalanche/avalanche/training/plugins.py", line 421, in after_eval
    self._update_metrics(strategy, 'after_eval')
  File "/content/avalanche/avalanche/training/plugins.py", line 343, in _update_metrics
    metric_result = getattr(metric, callback)(strategy)
  File "/content/avalanche/avalanche/evaluation/metrics/confusion_matrix.py", line 232, in after_eval
    return self._package_result(strategy)
  File "/content/avalanche/avalanche/evaluation/metrics/confusion_matrix.py", line 245, in _package_result
    cm_image = self._image_creator(exp_cm)
  File "/content/avalanche/avalanche/evaluation/metric_utils.py", line 71, in default_cm_image_creator
    xticks_rotation=xticks_rotation, values_format=values_format)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_plot/confusion_matrix.py", line 109, in plot
    xlabel="Predicted label")
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/artist.py", line 1101, in set
    return self.update(props)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/artist.py", line 1003, in _update_property
    return func(v)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_base.py", line 3782, in set_yticklabels
    minor=minor, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/axis.py", line 1716, in set_ticklabels
    for t in ticklabels:
TypeError: 'NoneType' object is not iterable
```

### CODE REVIEW

**Comment by digantamisra98** [comment]
@AndreaCossu Since the datatype is a PIL Image which is supported by WandB, I just fixed it by calling the WandB Image which makes the PIL format compatible. I've pushed the new code, however, still having the same issue.

**Comment by digantamisra98** [comment]
Also the test coverage fails because of MNIST not getting downloaded. Should I open a separate issue for this?

**Comment by AndreaCossu** [comment]
Thank you @digantamisra98 . I'll check the new version out and let you know. MNIST problems should be fixed soon.

**Comment by AndreaCossu** [comment]
Remember also to execute `pycodestyle avalanche` from the avalanche root project and fix the errors in order to make your code PEP8 compliant. This will be required to merge the PR.

**Comment by digantamisra98** [comment]
@AndreaCossu Fixed all Pep8 issues. Working on Confusion Matrix overwriting logging now.

**Comment by ggraffieti** [comment]
Hi @digantamisra98, thank you for your contribution. 
The bug regarding the MNIST download was solved yesterday, so you can simply pull from the original avalanche repository and push to your fork in order to clear the errors from the tests on your pull request.

**Comment by digantamisra98** [comment]
Thank you @ggraffieti for the quick fix.

**Comment by AndreaCossu** [comment]
Let me know when I can merge this @digantamisra98 :smile:

**Comment by digantamisra98** [comment]
@AndreaCossu I'll work on the section nesting now.

**Pull request merged**
