### PR TITLE
Fixed isinstance on Base Strategy to enable benchmarks with task label per pattern

### LINKED ISSUE #657: Benchmark with a task label per pattern fails on strategy.train() call
I am trying to train a `Naive` strategy on a fake benchmark where task labels are provided for each pattern. It seems that there is a call to `task_label` instead of `task_labels` which cause the code to fail (since `task_label` is not defined for this kind of benchmark). The error is raised on a `isinstance` check which makes it kind of hard to debug.

This is the code and the traceback:
```python
tr_ds = [AvalancheTensorDataset(torch.randn(10, 7, 3), torch.randint(0, 3, (10,)),
                                dataset_type=AvalancheDatasetType.CLASSIFICATION,
                                task_labels=torch.randint(0, 5, (10,)).tolist()) for i in range(3)]
ts_ds = [AvalancheTensorDataset(torch.randn(10, 7, 3), torch.randint(0, 3, (10,)),
                                dataset_type=AvalancheDatasetType.CLASSIFICATION,
                                task_labels=torch.randint(0, 5, (10,)).tolist()) for i in range(3)]
scenario = create_multi_dataset_generic_benchmark(train_datasets=tr_ds, test_datasets=ts_ds)
model = SimpleMLP(input_size=3, num_classes=2)
cl_strategy = Naive(model, SGD(model.parameters(), lr=0.001, momentum=0.9),
        CrossEntropyLoss(), train_mb_size=500, train_epochs=1, eval_mb_size=100,
        device='cpu', evaluator=None)
for i, experience in enumerate(scenario.train_stream):
    cl_strategy.train(experience)

Traceback (most recent call last):
  File "test.py", line 163, in <module>
    main(args)
  File "test.py", line 137, in main
    res = cl_strategy.train(experience)
  File "/home/acossu/avalanche/avalanche/training/strategies/base_strategy.py", line 221, in train
    if isinstance(experiences, Experience):
  File "/home/acossu/miniconda3/envs/avalanche-dev-env/lib/python3.8/typing.py", line 1017, in __instancecheck__
    if all(hasattr(instance, attr) and
  File "/home/acossu/miniconda3/envs/avalanche-dev-env/lib/python3.8/typing.py", line 1017, in <genexpr>
    if all(hasattr(instance, attr) and
  File "/home/acossu/avalanche/avalanche/benchmarks/scenarios/generic_cl_scenario.py", line 607, in task_label
    raise ValueError('The task_label property can only be accessed '
ValueError: The task_label property can only be accessed when the experience contains a single task label
```

### PR DESCRIPTION
**Pull request by AndreaCossu**
This closes #657 , implementing @lrzpellegrini 's suggestion. 

The `isinstance(experience, Experience)` call is modified to `not isinstance(experience, Sequence)`.

### CODE REVIEW

**Comment by lrzpellegrini** [comment]
Looks nice! However, a small regression unit test would be a nice-to-have thing.

**Comment by AntonioCarta** [comment]
Agree. If you can add a small test we can merge it.

**Comment by AndreaCossu** [comment]
Sure, I can add a unit test based on the issue solved by this PR. @lrzpellegrini aren't regression tests already present in the github actions?

**Comment by lrzpellegrini** [comment]
Regression tests currently don't have a specific GitHub action (I don't think it's needed). They just run with other unit tests. I think that the code you posted in the initial issue should work as a regression test.

**Comment by AndreaCossu** [comment]
I added the unit test. Up to now, loggers are not working in this kind of benchmark (the unit test uses `evaluator=None`). I will make a PR soon with metrics and loggers updated to manage also this case.

**Pull request merged**
