### PR TITLE
StreamForgetting

### PR DESCRIPTION
**Pull request by Mattdl**
The StreamForgetting is implemented as the average of the forgetting over all experiences. A forgetting_metrics helper method is implemented to create both the StreamForgetting and ExperienceForgetting metrics. The use is exemplified in the examples/eval_plugin.py

### CODE REVIEW

**Comment by Mattdl** [comment]
Closing #461

**Comment by vlomonaco** [comment]
That's awesome @Mattdl! @AndreaCossu will review it and merge it. In the meanwhile can you add also a test to satisfy the coverage requirements? thanks :)

**Comment by Mattdl** [comment]
Ok great, thanks! (: Yeah I was looking for this, but couldn't find any similar tests for MetricPlugins. Am I overlooking these or should I try to make one from scratch?
e.g. I could test the relation between the ExperienceForgetting and StreamForgetting is actually the average.

**Comment by ggraffieti** [comment]
Don't know why, but the failing options for the coverage were not saved. 
I'll run again the coverage tests, they should be fine.

**Comment by ggraffieti** [comment]
We can merge this PR, false fail of the test coverage. I should have fixed the bug for the following PRs.

**Comment by AndreaCossu** [comment]
Thanks @Mattdl, I'm going to review this in the next hours. Tests are something we need to discuss but for the moment I'm only testing the standalone metrics. It is not easy to test the plugin metrics since they require a training and evaluation loop. 
I'll take care of updating the documentation upon merging.

**Review by AndreaCossu — APPROVED** [review]

**Pull request merged**
