### PR TITLE
Refactor CLEAR Benchmark based on the official webpage

### PR DESCRIPTION
**Pull request by jd730**
According to the [CLEAR official wiki](https://linzhiqiu.gitbook.io/the-clear-benchmark/documentation/download-clear-10-clear-100), the download path is slightly changed although the previous one is still working now. Moreover, they removed other features except moco_b0. I changed it accordingly.

### CODE REVIEW

**Comment by AntonioCarta** [comment]
Thanks @jd730. The splits are the same as before?

**Comment by jd730** [comment]
@AntonioCarta Thank you for pointing this out. The up-to-date version does not have a validation split but is already divided. I will change `_load_metadata()` accordingly and let you know.

**Comment by jd730** [comment]
I changed the function following the updated directory structure. However, there is no `features` for the testset in the updated dataset. I haven't checked clear100 and will check later this week.

**Comment by jd730** [comment]
Hi @AntonioCarta, I checked that the current codebase is working for `clear10`, `clear100`, `clear_neurips2021`(previous version of`clear10`), and `clear10_cvpr2022`.
Could you check and merge it?

**Comment by AntonioCarta** [comment]
Thank you!

**Pull request merged**
