### PR TITLE
Replay with StoragePolicies and CoPE strategy

### PR DESCRIPTION
**Pull request by Mattdl**
This PR implements the following:

Replay:
- ReplayPlugin now uses an abstract StoragePolicy to determine which sample store in the replay memory.
- 2 implementations of the StoragePolicy are provided: ClassBalancedStoragePolicy & ExperienceBalancedStoragePolicy.
- Test for the different storage policies. 
- The implementation of ExperienceBalancedStoragePolicy solves the bug in #543 
-  Replay memory is fully filled with the available data: remaining data after dividing equally over experiences/classes, is divided at random taking into account the data available per experience/class.

CoPE:
- The CoPE plugin for online data incremental learning is implemented.
- The CoPE strategy wrapper.
- Testing for the CoPE strategy.
- A working example of the CoPEPlugin. This is a class-incremental setup example. The online data incremental setup still is to be implemented as discussed in #543, #360.

SimpleMLP
- Small update where the number of layers can be easily configured as well.

### CODE REVIEW

**Comment by Mattdl** [comment]
The PEP8 error didn't show locally. Also don't know how `l` is ambiguous in any way in the SimpleMLP.
Any ideas why this happens?

**Comment by lrzpellegrini** [comment]
Alas, it seems that PEP8 doesn't really like variables, classes, etc. named ‘l’, ‘O’, or ‘I’ no matter the context.

**Comment by AntonioCarta** [comment]
Thanks @Mattdl, everything looks good. Can I merge it?

**Comment by Mattdl** [comment]
Thanks! I've no further updates for this PR, so you can merge (:

**Pull request merged**
