### PR TITLE
Examples in docs

### PR DESCRIPTION
**Pull request by niniack**
### Adding code blocks as examples in the API Documentation

This PR is a result from discussion in Issue #886 and is inspired by PyTorch documentation ([here's an example](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html#:~:text=%3E%3E%3E%20m%20%3D%20nn.conv1d(16%2C%2033%2C%203%2C%20stride%3D2)))

#### Changes: 
- Update API docs footer to be 2022 (previously was 2021)
- Add examples to Simple CNN and SimpleMLP classes. It defaults to python syntax highlighting.
- Use the `sphinx_copybutton` extension to allow for users to quickly copy code blocks.

#### Notes:
- The `sphinx_copybutton` extension can be installed in the conda environment with [these instructions](https://pypi.org/project/sphinx-copybutton/)

**Before**:
 
avalanche-old

**After**:

avalanche-new

### CODE REVIEW

**Comment by AntonioCarta** [comment]
Thanks, it looks very nice. Can you add the dependency to `environment-dev.yml`?

**Comment by niniack** [comment]
I'm curious if the extent of those examples is enough? It didn't feel right to throw in a full model-training example

Generally, is that level of "depth" good for examples?

**Comment by AntonioCarta** [comment]
I think examples should be minimal. E.g. see [pytorch modules](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html?highlight=linear#torch.nn.Linear).

**Comment by AntonioCarta** [comment]
If you fix the pep8 I think we can merge this. You can use `pycodestyle` to check errors.

**Comment by AndreaCossu** [comment]
I think the dependency should also be added to `docs/requirements.txt`

**Comment by niniack** [comment]
Sounds good, I'll add the dep to `requirements.txt` and fix the PEP8 errors

**Comment by niniack** [comment]
Looks like format on save was turned off on previous commits which is why that pep8 error slipped by. Thanks for letting me help out, hopefully I can help out some more with examples + other areas

Good luck on the release!

**Comment by AntonioCarta** [comment]
Thanks @niniack, I will merge this. If you add other examples you can make other PRs, they should be much quicker now that we have all the dependencies in place.

**Pull request merged**
