### PR TITLE
Data incremental example CoPE

### PR DESCRIPTION
**Pull request by Mattdl**
Support needed for #616 , the Max recursion depth error was also a problem in a previous issue, where spawning new AvalancheDatasets per batch gets a too deep calling tree.

### CODE REVIEW

**Comment by vlomonaco** [comment]
Hi @Mattdl for sharing a code example next time I suggest to create a commit on your personal fork (and share the link) rather than opening a PR here! :-)

**Comment by Mattdl** [comment]
Hi @vlomonaco, makes sense! Other collaborators suggested making a PR with a [WIP] tag to show it's a draft PR.
So the policy has changed on this?

**Comment by vlomonaco** [comment]
Yes, @Mattdl actually I may myself have pointed you towards this earlier, sorry :) But given that now a few PR are stalling it would be good to have only future integrations here and not examples, thanks!

**Comment by Mattdl** [comment]
Ok I see! (: I actually wanted to merge this, because the CoPE example was still in the class-incremental setting.
Only afterwards the data-incremental setting was implemented, so I'm trying to update the example with this PR.

**Comment by lrzpellegrini** [comment]
Hi Matt, thank you for the great work!

Apart from the performance issues pointed out in #650 and #653 (which seem related to Avalanche internals more than CoPe itself), do you think that this PR ready to merge?

**Comment by AntonioCarta** [comment]
Before merging we should check that the data incremental example reaches the correct performance values. RIght now, it doesn't #650

**Comment by Mattdl** [comment]
Problem is that I can't yet reproduce the results when applying the data incremental generator, and the setup is now too cumbersome to debug 😄 But if you want to close this PR, there is a TODO in the example and I can make a new PR when the other issues are resolved (although it might be harder to have a clear history on all the PRs/issues together)

**Pull request merged**
