### PR TITLE
Fix for #593

### LINKED ISSUE #593: Bug in classes_in_this_experience on test set
The `classes_in_this_experience` does not work when applied to the complete test set of CoRE50. The test stream correctly contains all the 50 classes but the parameter returns only the first 10. 

I think the problem may be related to the fact that `LazyClassesInExps` only works with training experiences (which impacts on the experience factory generating the test stream). @lrzpellegrini can you provide help on this?
```
scenario = CORe50(scenario='nc')
print(len(scenario.test_stream))
print(scenario.test_stream[0].classes_in_this_experience)
```
Output:
```
»»» 1
»»» [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
Expected:
```
»»» 1
»»» [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ..., 49]
```

### PR DESCRIPTION
**Pull request by lrzpellegrini**
The `classes_in_this_experience` field of `GenericCLScenario` by default returned the list linked to the training stream. This made it difficult to obtain the list of classes for non-training experiences.

This PR introduces another way to use that field, which can now be used as:

```python
benchmark_instance.classes_in_experience[stream_name][exp_id]
```

The previous way to use this field is deprecated. The following:

```python
benchmark_instance.classes_in_experience[exp_id]  # Deprecated
```

still works, but a warning will be printed to stdout.

Fixes #593

### CODE REVIEW

**Comment by vlomonaco** [comment]
You mean 

`benchmark_instance.classes_in_experience[stream_name][exp_id]`

not:

`benchmark_instance.classes_in_this_experience[stream_name][exp_id]`

right?

**Comment by lrzpellegrini** [comment]
Yes, sorry it's `classes_in_experience`!

**Comment by lrzpellegrini** [comment]
There also seem to be problems with the experience level field. I'll fix it ASAP.

**Comment by AntonioCarta** [comment]
After this change it seems that the attribute belongs to the experience. Maybe it shouldn't be in the `GenericCLScenario` at all? it seems weird to use the dictionary instead of `benchmark_instance.stream_name.classes_in_this_experience[exp_id]`.

**Comment by lrzpellegrini** [comment]
Users can currently access the list of classes through

```python
benchmark_instance.classes_in_experience[stream][exp]
```

or 

```python
benchmark_instance.xxx_stream[exp].classes_in_this_experience
```

The result is the same. For the moment I'd go with this plain fix. In the future we may consider re-organizing this mechanism.

**Comment by vlomonaco** [comment]
It's ok for me. What's really important IMHO is that `experience.classes_in_this_experience` works as expected!

**Comment by AndreaCossu** [comment]
Thanks @lrzpellegrini, ok for me!

**Comment by AntonioCarta** [comment]
> 
> 
> Users can currently access the list of classes through
> 
> ```python
> benchmark_instance.classes_in_experience[stream][exp]
> ```
> 
> or
> 
> ```python
> benchmark_instance.xxx_stream[exp].classes_in_this_experience
> ```
> 
> The result is the same. For the moment I'd go with this plain fix. In the future we may consider re-organizing this mechanism.

Right, I forgot you could already do it. I would probably remove `benchmark_instance.classes_in_experience` since it's redundant, but it's fine if you prefer it this way.

**Pull request merged**
